src/AppBundle/Entity/Message.php
<?php

namespace Raddit\AppBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\MappedSuperclass()
 */
abstract class Message {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue()
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User|null
     */
    private $sender;

    /**
     * @ORM\Column(type="text")
     *
     * @var string|null
     */
    private $body;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="inet")
     *
     * @var string|null
     */
    private $ip;

    public function __construct() {
        $this->timestamp = new \DateTime('@'.time());
    }

    /**
     * @return int|null
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @return User|null
     */
    public function getSender() {
        return $this->sender;
    }

    /**
     * @param User|null $sender
     */
    public function setSender($sender) {
        $this->sender = $sender;
    }

    /**
     * @return string|null
     */
    public function getBody() {
        return $this->body;
    }

    /**
     * @param string|null $body
     */
    public function setBody($body) {
        $this->body = $body;
    }

    /**
     * @return \DateTime
     */
    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    /**
     * @param \DateTime $timestamp
     */
    public function setTimestamp(\DateTime $timestamp) {
        $this->timestamp = $timestamp;
    }

    /**
     * @return string|null
     */
    public function getIp() {
        return $this->ip;
    }

    /**
     * @param string|null $ip
     */
    public function setIp($ip) {
        $this->ip = $ip;
    }

    /**
     * @return Notification[]|Collection|Selectable
     */
    abstract public function getNotifications();
}

src/AppBundle/Resources/views/includes/meta_pagination.html.twig
{% with {attr: app.request.attributes} %}
  {% if pager.hasPreviousPage %}
    <link rel="prev" href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.previousPage})) }}">
  {% endif %}

  {% if pager.hasNextPage %}
    <link rel="next" href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.nextPage})) }}">
  {% endif %}
{% endwith %}

src/AppBundle/Resources/views/includes/pagination.html.twig
{% with {attr: app.request.attributes} %}
  <nav class="pagination">
    <ul>
      {% if pager.hasPreviousPage %}
        <li class="previous">
          <a href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.previousPage})) }}">
            {{ 'pagination.previous'|trans }}
          </a>
        </li>
      {% endif %}
      {% if pager.hasNextPage %}
        <li class="next">
          <a href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.nextPage})) }}">
            {{ 'pagination.next'|trans }}
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endwith %}

src/AppBundle/Resources/views/includes/site_nav.html.twig
{% spaceless %}
  <nav class="site-nav">
    <ul>
      <li><a href="{{ path('raddit_app_front') }}">{{ raddit_app_site_name() }}</a></li>
      <li><a href="{{ path('raddit_app_forum_list') }}">{{ 'site_nav.forum_list'|trans }}</a></li>
      <li><a href="{{ path('raddit_app_wiki') }}">{{ 'site_nav.wiki'|trans }}</a></li>
    </ul>

    <ul class="right-nav">
      {% if not is_granted('ROLE_USER') %}
        <li><a href="{{ path('raddit_app_login') }}">{{ 'site_nav.log_in'|trans }}</a></li>
        <li><a href="{{ path('raddit_app_registration') }}">{{ 'site_nav.register'|trans }}</a></li>
      {% else %}
        {% with {notification_count: app.user.notifications|length} %}
        {% if notification_count > 0 %}
          <li class="has-notifications"><a href="{{ path('raddit_app_inbox') }}">{{ 'site_nav.inbox'|trans({'%count%': '<strong>%d</strong>'|format(notification_count)})|raw }}</a></li>
        {% endif %}
        {% endwith %}
        <li><a href="{{ path('raddit_app_submit', {forum_name: forum is defined and forum ? forum.name : null}) }}">{{ 'site_nav.submit'|trans }}</a></li>
        <li class="dropdown-container">
          <a href="#" class="dropdown-toggle"><strong>{{ app.user.username }}</strong></a>
          <ul class="dropdown-menu">
            <li><a href="{{ path('raddit_app_user', {username: app.user.username}) }}"><span class="icon icon-user"></span> {{ 'site_nav.profile'|trans }}</a></li>
            <li><a href="{{ path('raddit_app_message_list') }}"><span class="icon icon-mail"></span> {{ 'site_nav.messages'|trans }}</a></li>
            <li><a href="{{ path('raddit_app_edit_user', {username: app.user.username}) }}"><span class="icon icon-lock"></span> {{ 'site_nav.my_account'|trans }}</a></li>
            <li><a href="{{ path('raddit_app_user_settings', {username: app.user.username}) }}"><span class="icon icon-settings"></span> {{ 'site_nav.user_settings'|trans }}</a></li>
            <li><a href="{{ logout_path() }}"><span class="icon icon-logout"></span> {{ 'site_nav.log_out'|trans }}</a></li>
          </ul>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endspaceless %}